/*
 * Autogenerated By LRTT Auto Reverse (0.2)
 */
 
enum MenuStyle {
    LIGHT = 1,
    LIGHT_TRANSLUCENT = 2,
    DARK_TRANSLUCENT = 3;
}

enum Feature {
    GEOLOCATION = 1,
    ADVERTISING_ID = 2,
    BLUETOOTH_LE = 3,
    QR_CODE = 4,
    ADVERTISING_SDK = 5,
    ADD_TO_HOME = 6,
    SHARE_TARGET_MESSAGE = 7,
    VIDEO_AUTO_PLAY = 8,
    PROFILE_PLUS = 9;
}

enum LaunchOption {
    ALLOW_DIRECT_LINK = 1;
}

struct LiffNoneContext {
}

struct LiffChatContext {
    1: string chatMid;
}

struct LiffSquareChatContext {
    1: string squareChatMid;
}

struct LiffContext {
    1: LiffNoneContext none,
    2: LiffChatContext chat,
    3: LiffSquareChatContext squareChat;
}

struct LiffAdvertisingId {
    1: string advertisingId,
    2: bool tracking;
}

struct LiffDeviceSetting {
    1: bool videoAutoPlayAllowed,
    2: LiffAdvertisingId advertisingId;
}

struct LiffViewRequest {
    1: string liffId,
    2: LiffContext context,
    3: string lang,
    4: LiffDeviceSetting deviceSetting;
}

struct LiffView {
    1: string type,
    2: string url,
    4: i32 titleTextColor,
    5: i32 titleBackgroundColor,
    6: string titleIconUrl,
    7: i32 titleSubtextColor,
    8: i32 titleButtonColor,
    9: i32 progressBarColor,
    10: i32 progressBackgroundColor,
    11: bool trustedDomain,
    12: bool suspendable,
    13: bool maxBrightness,
    14: i32 titleButtonAreaBackgroundColor,
    15: i32 titleButtonAreaBorderColor,
    16: bool suspendableV2,
    17: MenuStyle menuStyle,
    18: bool moduleMode,
    19: i32 pinToHomeServiceId;
}

struct LiffViewResponse {
    1: LiffView view,
    2: string contextToken,
    3: string accessToken,
    4: string featureToken,
    5: list<Feature> features,
    6: string channelId,
    7: string idToken,
    8: list<string> scopes,
    9: list<LaunchOption> launchOptions;
}

struct RevokeTokenRequest {
    1: string accessToken;
}

service LiffService {
    LiffViewResponse issueLiffView (
        1: LiffViewRequest request;
    )

    void revokeToken (
        1: RevokeTokenRequest request;
    )

}
